In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.optimize as opt
from sklearn import preprocessing

In [2]:
import scipy.optimize as opt
from sklearn import preprocessing

In [77]:
df=pd.read_csv("train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [78]:
test=pd.read_csv("test.csv")
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [79]:
dummy1=pd.get_dummies(df["Sex"])

In [80]:
df=pd.concat([df,dummy1],axis=1)

In [81]:
x=df[["Pclass","male","female"]]

In [82]:
y=df[["Survived"]]

In [83]:
%matplotlib notebook

In [84]:
x2=np.asarray(df[["Pclass","male","female","SibSp", "Parch"]])
x2[:5]

array([[3, 1, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [3, 0, 1, 0, 0],
       [1, 0, 1, 1, 0],
       [3, 1, 0, 0, 0]], dtype=int64)

In [85]:
y2=np.asarray(df["Survived"])

In [86]:
x2=preprocessing.StandardScaler().fit(x2).transform(x2)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
from sklearn.metrics import confusion_matrix

In [87]:
print ('Train set:', x2.shape,  y2.shape)
#print ('Test set:', X_test.shape,  y_test.shape)

Train set: (891, 5) (891,)


In [88]:
dummy1=pd.get_dummies(test["Sex"])

In [89]:
test=pd.concat([test,dummy1],axis=1)

In [90]:
x_test=np.asarray(test[["Pclass","male","female","SibSp", "Parch"]])
x_test[:5]

array([[3, 1, 0, 0, 0],
       [3, 0, 1, 1, 0],
       [2, 1, 0, 0, 0],
       [3, 1, 0, 0, 0],
       [3, 0, 1, 1, 1]], dtype=int64)

In [21]:
#y_test=np.asarray(test["Survived"])

In [91]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x2,y2)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [92]:
x_test

array([[3, 1, 0, 0, 0],
       [3, 0, 1, 1, 0],
       [2, 1, 0, 0, 0],
       ...,
       [3, 1, 0, 0, 0],
       [3, 1, 0, 0, 0],
       [3, 1, 0, 1, 1]], dtype=int64)

In [93]:
x2

array([[ 0.82737724,  0.73769513, -0.73769513,  0.43279337, -0.47367361],
       [-1.56610693, -1.35557354,  1.35557354,  0.43279337, -0.47367361],
       [ 0.82737724, -1.35557354,  1.35557354, -0.4745452 , -0.47367361],
       ...,
       [ 0.82737724, -1.35557354,  1.35557354,  0.43279337,  2.00893337],
       [-1.56610693,  0.73769513, -0.73769513, -0.4745452 , -0.47367361],
       [ 0.82737724,  0.73769513, -0.73769513, -0.4745452 , -0.47367361]])

In [94]:
x_test=preprocessing.StandardScaler().fit(x_test).transform(x_test)
x_test[:5]

array([[ 0.87348191,  0.75592895, -0.75592895, -0.49947002, -0.4002477 ],
       [ 0.87348191, -1.32287566,  1.32287566,  0.61699237, -0.4002477 ],
       [-0.31581919,  0.75592895, -0.75592895, -0.49947002, -0.4002477 ],
       [ 0.87348191,  0.75592895, -0.75592895, -0.49947002, -0.4002477 ],
       [ 0.87348191, -1.32287566,  1.32287566,  0.61699237,  0.61989583]])

In [95]:
yhat=LR.predict(x_test)
yhat

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [96]:
output = pd.DataFrame({'PassengerId': test.PassengerId, 'Survived': yhat})
output.to_csv('my_submission3.csv', index=False)

In [32]:
yemp=pd.read_csv("my_submission.csv")
yemp

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [54]:
x2=np.asarray(df[["Pclass","male","female","Age"]])
x2[:5]

array([[ 3.,  1.,  0., 22.],
       [ 1.,  0.,  1., 38.],
       [ 3.,  0.,  1., 26.],
       [ 1.,  0.,  1., 35.],
       [ 3.,  1.,  0., 35.]])

In [55]:
x2=preprocessing.StandardScaler().fit(x2).transform(x2)
x2[:5]

array([[ 0.91123237,  0.75905134, -0.75905134, -0.53037664],
       [-1.47636364, -1.31743394,  1.31743394,  0.57183099],
       [ 0.91123237, -1.31743394,  1.31743394, -0.25482473],
       [-1.47636364, -1.31743394,  1.31743394,  0.36516706],
       [ 0.91123237,  0.75905134, -0.75905134,  0.36516706]])

In [56]:
x_test=np.asarray(test[["Pclass","male","female","Age"]])
x_test[:5]

array([[ 3. ,  1. ,  0. , 34.5],
       [ 3. ,  0. ,  1. , 47. ],
       [ 2. ,  1. ,  0. , 62. ],
       [ 3. ,  1. ,  0. , 27. ],
       [ 3. ,  0. ,  1. , 22. ]])

In [57]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x2,y2)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
df.dropna(subset=["Age"],axis=0,inplace=True)

In [39]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  female  male  
0        0         A/5 21171   7.2500   NaN        S       0     1  
1        0          PC 17599  71.2833   C85        C       1     0  
2        0  STON/O2. 3101282   7.9250   NaN        S       1     0  
3        0            113803  53.1000  C123        S       1     0  
4        0            373450   8.0500   NaN        S       0     1  
..     ...               ...      ...   ...      ...     ...   ...  
885      5            382652  29.1250   NaN        Q       1     0  
886      0            211536  13.0000   NaN        S       0     1  
887      0            112053  30.0000   B42        S       1     0  
889      0            111369  30.0000  C148        C       0     1  
890      0            370376   7.7500   NaN        Q       0     1  

[714 rows x 14 columns]

In [42]:
test.dropna(subset=["Age"],axis=0,inplace=True)

In [69]:
x_test=np.asarray(test[["Pclass","male","female","Age"]])
x_test[:5]

array([[ 3. ,  1. ,  0. , 34.5],
       [ 3. ,  0. ,  1. , 47. ],
       [ 2. ,  1. ,  0. , 62. ],
       [ 3. ,  1. ,  0. , 27. ],
       [ 3. ,  0. ,  1. , 22. ]])

In [44]:
x2=np.asarray(df[["Pclass","male","female","Age"]])
x2[:5]
x2=preprocessing.StandardScaler().fit(x2).transform(x2)

In [59]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x2,y2)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [60]:
y2=np.asarray(df["Survived"])
y2[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [61]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x2,y2)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [70]:
x_test=preprocessing.StandardScaler().fit(x_test).transform(x_test)


In [72]:
yhat=LR.predict(x_test)
print(yhat)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [64]:
output = pd.DataFrame({'PassengerId': test.PassengerId, 'Survived': yhat})
output.to_csv('my_submission_2.csv', index=False)